name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10, 12, 14 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup node_modules Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: yarn build --if-present
        env:
          CI: true

      - name: Install Dependencies for Example Project
        if: matrix.node-version == 14
        run: yarn --cwd example install --frozen-lockfile
        env:
          CI: true

      - name: Build Example Project
        if: matrix.node-version == 14
        run: yarn --cwd example build
        env:
          CI: true

      - name: Upload Documentation Artifact
        if: matrix.node-version == 14
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: example/dist

  update-github-pages:
    needs: build
    name: Update Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull

      - name: Delete existing Documentation
        run: find docs ! -name '_config.yml' -type f -exec rm -f {} +

      - name: Download Documentation Artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: docs

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update Documentation"
          git push
