name: Publish

on:
  release:
    types: [ created ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile
        env:
          CI: true

      - run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

  publish-npm:
    needs: test
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: yarn install --frozen-lockfile
        env:
          CI: true

      - run: yarn publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
