name: Publish

on:
  release:
    types: [ created ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install --frozen-lockfile
        env:
          CI: true

      - run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

  publish-npm:
    needs: test
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update Project Version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Push Changes
        run: git push

      - run: yarn install --frozen-lockfile
        env:
          CI: true

      - run: yarn publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
